[package]
name = "file-share"
version = "0.1.0"
edition = "2021"
authors = ["Maneren <maneren731@gmail.com>"]
license = "MIT"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.5.0-rc1", features = ["nightly"] }
leptos_axum = { version = "0.5.0-rc1", optional = true }
leptos_meta = { version = "0.5.0-rc1", features = ["nightly"] }
leptos_router = { version = "0.5.0-rc1", features = ["nightly"] }
leptos-use = { git = "https://github.com/synphonyte/leptos-use" } # use git until 0.5.0 support is released

axum = { version = "0.6", optional = true, features = ["multipart"] }
cfg-if = "1"
chrono = "0.4"
chrono-humanize = "0.2"
clap = { version = "4.4", features = ["derive"], optional = true }
colored = { version = "2", optional = true }
console_error_panic_hook = "0.1"
console_log = "1"
fast_qr = { version = "0.10", optional = true }
futures = { version = "0.3", optional = true }
http = "0.2.9"
if-addrs = { version = "0.10", optional = true }
js-sys = { version = "0.3" }
libflate = { version = "2.0", optional = true }
log = "0.4"
phf = { version = "0.11", features = ["macros"] }
port_check = { version = "0.1", optional = true }
rust-embed = { version = "8.0", features = [
  "interpolate-folder-path",
  "mime-guess",
], optional = true }
serde = { version = "1", features = ["derive"] }
simple_logger = "4"
tar = { version = "0.4", optional = true }
thiserror = "1"
tokio = { version = "1.32", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.4", features = ["fs"], optional = true }
tracing = { version = "0", optional = true }
wasm-bindgen = "=0.2.87"
wasm-bindgen-futures = "=0.4.37"
web-sys = { version = "0.3", features = [
  "File",
  "FileList",
  "HtmlInputElement",
  "Blob",
  "ReadableStream",
] }
zip = { version = "0.6", optional = true }
zstd = { version = "0.12", optional = true }

# internal proc macro helper
icons_helper = { version = "0.0.0", path = "src/icons_helper" }

[profile.dev.package.leptos_macro]
opt-level = 3

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "dep:axum",
  "dep:clap",
  "dep:colored",
  "dep:fast_qr",
  "dep:futures",
  "dep:if-addrs",
  "dep:leptos_axum",
  "dep:libflate",
  "dep:port_check",
  "dep:rust-embed",
  "dep:tar",
  "dep:tokio",
  "dep:tower",
  "dep:tower-http",
  "dep:tracing",
  "dep:zip",
  "dep:zstd",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
output-name = "file-share"
style-file = "style/main.scss"
assets-dir = "public"
lib-profile-release = "wasm-release"

bin-features = ["ssr"]
lib-features = ["hydrate"]
