name: Test building binaries
on:
  pull_request:
jobs:
  build-for-release:
    name: Build and release
    strategy:
      matrix:
        job:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.job.target }}
      os: ${{ matrix.job.os }}
